### ISSUE TITLE
wp-bootstrap-navwalker dropdowns NOT working.

### ISSUE THREAD

**Issue by AngeloAlves** [wp-bootstrap/wp-bootstrap-navwalker#76]
I installed the required code into the respective files and updated the "wp-bs-nw.php" file to the "theme" directory.

http://www.auxilliumit.com 

I started setting up menus in wordpress. When I went to test them I got no 
"About .> Services" sublink

I have tried everything including a dozen other plugins. Thought the dropdown isn't working this resource at least actually works with the wordpress custom menus 

Please help, on a deadline and freaking out LOL

**Comment by SideQuestDIY** [comment]
No problem. 99.9% of the time this is due to the JavaScript files not being loaded into the theme correctly. If you take a look at the solved issues there are 3 or 4 copies of the same issue that have been solved. I am currently at a hockey game but I will gladly help you out when I return.

**Comment by AngeloAlves** [comment]
Hey Edward, 

Look forward to hearing from you soon. 

I’m aiming to launch the business for spring. WP/BS Collaboration are new to me.

Thanks,

-Angelo

**Comment by AngeloAlves** [comment]
Hey Edward,

Just wanted to follow up with you and see if you had a chance to look into my issue with drop down not working. 

Thanks,

Angelo

**Comment by csoutham** [comment]
Make sure you include the bootstrap.js file too - that'll fix your problem.

**Comment by AngeloAlves** [comment]
I just tried including bootstrap.js as shown below and it's still not working.
<?php

function wpbootstrap_scripts_with_jquery()
{
    // Register the script like this for a theme:
    wp_register_script( 'custom-script-min', get_template_directory_uri() . '/bootstrap/js/bootstrap.min.js', array( 'jquery' ) );
    wp_register_script( 'custom-script', get_template_directory_uri() . '/bootstrap/js/bootstrap.js', array( 'jquery' ) );
    // For either a plugin or a theme, you can then enqueue the script:
    wp_enqueue_script( 'custom-script-min' );
    wp_enqueue_script( 'custom-script' );
}

// Register Custom Navigation Walker
require_once('wp_bootstrap_navwalker.php');

register_nav_menus( array(
    'primary' => __( 'Primary Menu', 'bootstrap' ),
) );

?>

**Comment by csoutham** [comment]
Ok, I would include one of each of the JS file, so bootstrap.js or bootstrap.min.js. Same for custom script.
Then you need to call the function to queue the files.
Add this line after the wpbootstrap_scripts_with_jquery function

```
add_action( 'wp_enqueue_scripts', 'wpbootstrap_scripts_with_jquery' );
```

If it's still not working, make sure all of that is pushed to your test URL above and I'll take another look.

**Comment by AngeloAlves** [comment]
It just gets better and better..

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

**Comment by csoutham** [comment]
Hmmm, well remove that line then!
This hasn't got a lot to do with the bootstrap-navwalker and more to do with your understanding of how to put together a WordPress theme.
I'm nothing to do with this really, just a user trying to help you out but it seems you may be trying to run before you can walk on this one.

**Comment by AngeloAlves** [comment]
LOL... Thanks for your help I'll have to keep trying. It's probably right under my nose!

**Comment by csoutham** [comment]
Happy to take a look at the code for you, but I can't see any of it at the moment - makes it a lot harder to help.

**Comment by AngeloAlves** [comment]
I'd be happy to send you what I have. Which files are you looking for specifically? And where do I send them?

**Comment by csoutham** [comment]
Either send me your FTP details, or send me your functions.php file - to me at csoutham dot com.

**Comment by AngeloAlves** [comment]
ftp █████████████
user █████████
pw ██████████

contact me further at me at angeloalves dot com

**Comment by csoutham** [comment]
Hey! Just to prove it is the JS file I've added it to your header.php - I couldn't get it to work properly via the functions.php enqueue and since I can't see any debugging information it makes it hard to work out why.
Hopefully you can see the dropdown now :)

**Comment by AngeloAlves** [comment]
works great thanks!
I can get you access to the server logs if you're interested finding out more about that issue I'm curious myself

**Comment by SideQuestDIY** [comment]
@AngeloAlves Sorry I couldn't take a look at this sooner. 

@ChrisSoutham Your the man! Thanks for lending a hand!
